#ifndef _FCEU_VSUNI_H
#define _FCEU_VSUNI_H

void FCEU_VSUniPower(void);
void FCEU_VSUniCheck(uint64 md5partial, int *, uint8 *);
void FCEU_VSUniDraw(uint8 *XBuf);

void FCEU_VSUniToggleDIP(int);	/* For movies and netplay */
void FCEU_VSUniCoin(void);
void FCEU_VSUniSwap(uint8 *j0, uint8 *j1);

enum {
	VS_BASEBALL = 1,
	VS_BATTLECITY,
	VS_CASTLEVANIA,
	VS_CLUCLULAND,
	VS_DRMARIO,
	VS_DUCKHUNT,
	VS_EXITEBIKE,
	VS_FREEDOMFORCE,
	VS_GOONIES,
	VS_GRADIUS,
	VS_GUMSHOE,
	VS_HOGANSALLEY,
	VS_ICECLIMBER,
	VS_JAJAMARU,
	VS_LADIESGOLF,
	VS_MACHRIDER,
	VS_MIGHTYBOMBJACK,
	VS_PINBALL,
	VS_PLATOON,
	VS_RBIBASEBALL,
	VS_SLALOM,
	VS_SMB,
	VS_SOCCER,
	VS_STARLUSTER,
	VS_STROKEANDMATCHGOLF,
	VS_SUPERSKYKID,
	VS_SUPERXEVIOUS,
	VS_TETRIS,
	VS_TKOBOXING,
	VS_TOPGUN
};

#endif
